enum ErrorCode {
  SUCCESS = 'SUCCESS',
  FILE_READ_ERROR = 'FILE_READ_ERROR',
  FILE_SAVE_ERROR = 'FILE_SAVE_ERROR',
  SERVER_UPLOAD_ERROR = 'SERVER_UPLOAD_ERROR',
  SERVER_DOWNLOAD_ERROR = 'SERVER_DOWNLOAD_ERROR'
}

export default ErrorCode;
